name: SumberBaru
description: "Absensi Sumber Baru ban."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Core Packages
  http: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2  # Moved here (Critical Fix)
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.0.0

  # Features
  geolocator: ^14.0.2
  image_picker: ^1.0.7
  file_picker: ^10.3.10
  open_file: ^3.3.0
  onesignal_flutter: ^5.4.1

  # UI & PDF
  cupertino_icons: ^1.0.8
  flutter_cached_pdfview: ^0.4.2
  pdf: ^3.10.0
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  assets:
    - lib/assets/sbb-removebg-preview.png
    - lib/assets/Gemini_Generated_Image_7461ma7461ma7461.png
    - lib/assets/spooring-berkala.jpg
  uses-material-design: true
